// utils/featureFlags.ts

export enum FeatureFlagKeys {
  // Root Feature
  ENABLE = "ENABLE",

  // Parent Feature
  ENABLE_SETTINGS = "ENABLE_SETTINGS",

  // Sub-Sections and Features under AuthModal
  ENABLE_AUTH_MODAL = "ENABLE_AUTH_MODAL",
  ENABLE_AUTH_MODAL_WELCOME_VIEW = "ENABLE_AUTH_MODAL_WELCOME_VIEW",
  ENABLE_AUTH_MODAL_SIGNUP_VIEW = "ENABLE_AUTH_MODAL_SIGNUP_VIEW",
  ENABLE_AUTH_MODAL_LOGIN_VIEW = "ENABLE_AUTH_MODAL_LOGIN_VIEW",
  ENABLE_AUTH_MODAL_SETUSERNAME_VIEW = "ENABLE_AUTH_MODAL_SETUSERNAME_VIEW",
  ENABLE_AUTH_MODAL_TOASTS = "ENABLE_AUTH_MODAL_TOASTS",
  ENABLE_AUTH_MODAL_ANIMATIONS = "ENABLE_AUTH_MODAL_ANIMATIONS",
  ENABLE_AUTH_MODAL_FOOTER = "ENABLE_AUTH_MODAL_FOOTER",
  ENABLE_AUTH_MODAL_BACK_BUTTON = "ENABLE_AUTH_MODAL_BACK_BUTTON",
  ENABLE_AUTH_MODAL_CONTEXT_MESSAGE = "ENABLE_AUTH_MODAL_CONTEXT_MESSAGE",
  ENABLE_AUTH_MODAL_ERROR_MESSAGES = "ENABLE_AUTH_MODAL_ERROR_MESSAGES",

  // Main Tabs under ENABLE_SETTINGS
  ENABLE_SETTINGS_ACCOUNT = "ENABLE_SETTINGS_ACCOUNT",
  ENABLE_SETTINGS_SECURITY = "ENABLE_SETTINGS_SECURITY",
  ENABLE_SETTINGS_AFFILIATES = "ENABLE_SETTINGS_AFFILIATES",
  ENABLE_SETTINGS_OPTIONS = "ENABLE_SETTINGS_OPTIONS",
  ENABLE_SETTINGS_TRANSACTIONS = "ENABLE_SETTINGS_TRANSACTIONS",

  // Sub-Sections and Features under ENABLE_SETTINGS_ACCOUNT
  ENABLE_SETTINGS_ACCOUNT_BONUS_XP = "ENABLE_SETTINGS_ACCOUNT_BONUS_XP",
  ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY = "ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY",
  ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES = "ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES",
  ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL = "ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL",
  ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS = "ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS",
  ENABLE_SETTINGS_ACCOUNT_SELF_LOCK = "ENABLE_SETTINGS_ACCOUNT_SELF_LOCK",

  // Sub-Sections and Features under ENABLE_SETTINGS_SECURITY
  ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH = "ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH",
  ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS = "ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS",
  ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE = "ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE",

  // Sub-Sections and Features under ENABLE_SETTINGS_AFFILIATES
  ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE = "ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE",
  ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS = "ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS",
  ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS = "ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS",
  ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS = "ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS",

  // Sub-Sections and Features under ENABLE_SETTINGS_OPTIONS
  ENABLE_SETTINGS_OPTIONS_ACCOUNT = "ENABLE_SETTINGS_OPTIONS_ACCOUNT",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS",
  ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS = "ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS_UNLINK_STEAM = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS_UNLINK_STEAM",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE",
  ENABLE_SETTINGS_OPTIONS_AUDIO = "ENABLE_SETTINGS_OPTIONS_AUDIO",
  ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME = "ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME",
  ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME = "ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME",
  ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME = "ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME",
  ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS = "ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS",
  ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS = "ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS",
  ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS = "ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS",
  ENABLE_SETTINGS_OPTIONS_DEV_MODE = "ENABLE_SETTINGS_OPTIONS_DEV_MODE",
  ENABLE_SETTINGS_OPTIONS_FAIRNESS = "ENABLE_SETTINGS_OPTIONS_FAIRNESS",

  // Sub-Sections and Features under ENABLE_SETTINGS_TRANSACTIONS
  ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE = "ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE",
  ENABLE_SETTINGS_TRANSACTIONS_PAGINATION = "ENABLE_SETTINGS_TRANSACTIONS_PAGINATION",

  // Sub-Sections and Features under MainPage
  ENABLE_MAINPAGE_USER_PROFILE = "ENABLE_MAINPAGE_USER_PROFILE",
  ENABLE_MAINPAGE_LIVE_FEED = "ENABLE_MAINPAGE_LIVE_FEED",
  ENABLE_MAINPAGE_RECENT_POSTS = "ENABLE_MAINPAGE_RECENT_POSTS",
  ENABLE_MAINPAGE_NEWS = "ENABLE_MAINPAGE_NEWS",
  ENABLE_MAINPAGE_CHANGELOG = "ENABLE_MAINPAGE_CHANGELOG",
  ENABLE_MAINPAGE_QUICK_ACTIONS = "ENABLE_MAINPAGE_QUICK_ACTIONS",
  ENABLE_MAINPAGE_USER_STATS = "ENABLE_MAINPAGE_USER_STATS",
  ENABLE_MAINPAGE_SERVER_STATUS = "ENABLE_MAINPAGE_SERVER_STATUS",
  ENABLE_MAINPAGE_BLOG_POSTS = "ENABLE_MAINPAGE_BLOG_POSTS",
  ENABLE_MAINPAGE_COMMUNITY_FEEDBACK = "ENABLE_MAINPAGE_COMMUNITY_FEEDBACK",

  // Sub-Sections and Features under UserProfileCard
  ENABLE_USERPROFILE_ACHIEVEMENTS = "ENABLE_USERPROFILE_ACHIEVEMENTS",
  ENABLE_USERPROFILE_STATS = "ENABLE_USERPROFILE_STATS",
  ENABLE_USERPROFILE_RANK = "ENABLE_USERPROFILE_RANK",

  // Sub-Sections and Features under UserStatsCard
  ENABLE_USERSTATS_RATING = "ENABLE_USERSTATS_RATING",
  ENABLE_USERSTATS_PROGRESS = "ENABLE_USERSTATS_PROGRESS",
  ENABLE_USERSTATS_TOTAL_JUMPS = "ENABLE_USERSTATS_TOTAL_JUMPS",
  ENABLE_USERSTATS_AVG_SPEED = "ENABLE_USERSTATS_AVG_SPEED",
  ENABLE_USERSTATS_FAVORITE_MAP = "ENABLE_USERSTATS_FAVORITE_MAP",
  ENABLE_USERSTATS_RANK = "ENABLE_USERSTATS_RANK",
  ENABLE_USERSTATS_XP_LEVEL = "ENABLE_USERSTATS_XP_LEVEL",

  // Sub-Sections and Features under ServerStatusCard
  ENABLE_SERVERSTATUS_CARD = "ENABLE_SERVERSTATUS_CARD",
  ENABLE_SERVERSTATUS_JOIN_BUTTON = "ENABLE_SERVERSTATUS_JOIN_BUTTON",
  ENABLE_SERVERSTATUS_TOOLTIPS = "ENABLE_SERVERSTATUS_TOOLTIPS",

  // Sub-Sections and Features under LiveFeedCard
  ENABLE_LIVEFEED_CARD = "ENABLE_LIVEFEED_CARD",
  ENABLE_LIVEFEED_DIALOG = "ENABLE_LIVEFEED_DIALOG",

  // Sub-Sections and Features under NewsCard
  ENABLE_NEWSCARD = "ENABLE_NEWSCARD",
  ENABLE_NEWSCARD_VIEW_ALL = "ENABLE_NEWSCARD_VIEW_ALL",
  ENABLE_NEWSCARD_POST_LIST = "ENABLE_NEWSCARD_POST_LIST",
  ENABLE_NEWSCARD_REACTIONS = "ENABLE_NEWSCARD_REACTIONS",
  ENABLE_NEWSCARD_POPOVER = "ENABLE_NEWSCARD_POPOVER",

  // Sub-Sections and Features under RecentPostsCard
  ENABLE_RECENTPOSTS_CARD = "ENABLE_RECENTPOSTS_CARD",
  ENABLE_RECENTPOSTS_VIEW_ALL = "ENABLE_RECENTPOSTS_VIEW_ALL",
  ENABLE_RECENTPOSTS_POST_LIST = "ENABLE_RECENTPOSTS_POST_LIST",

  // Sub-Sections and Features under QuickActionsCard
  ENABLE_QUICKACTIONS_CARD = "ENABLE_QUICKACTIONS_CARD",
  ENABLE_QUICKACTIONS_HOVER_OVERLAY = "ENABLE_QUICKACTIONS_HOVER_OVERLAY",

  // Sub-Sections and Features under BlogPostsCard
  ENABLE_BLOG_POSTS_CARD = "ENABLE_BLOG_POSTS_CARD",
  ENABLE_BLOG_POSTS_VIEW_ALL = "ENABLE_BLOG_POSTS_VIEW_ALL",

  // Sub-Sections and Features under SteamAuthModal
  ENABLE_STEAM_AUTH_MODAL = "ENABLE_STEAM_AUTH_MODAL",
  ENABLE_STEAM_AUTH_MODAL_ANIMATIONS = "ENABLE_STEAM_AUTH_MODAL_ANIMATIONS",
  ENABLE_STEAM_AUTH_MODAL_RELAUNCH_BUTTON = "ENABLE_STEAM_AUTH_MODAL_RELAUNCH_BUTTON",
  ENABLE_STEAM_AUTH_MODAL_POPUP_FEATURE = "ENABLE_STEAM_AUTH_MODAL_POPUP_FEATURE",
  ENABLE_STEAM_AUTH_MODAL_FOOTER = "ENABLE_STEAM_AUTH_MODAL_FOOTER",
  ENABLE_STEAM_AUTH_MODAL_ERROR_MESSAGES = "ENABLE_STEAM_AUTH_MODAL_ERROR_MESSAGES",
  ENABLE_STEAM_AUTH_MODAL_CONTEXT_MESSAGE = "ENABLE_STEAM_AUTH_MODAL_CONTEXT_MESSAGE",
  ENABLE_STEAM_AUTH_MODAL_TOASTS = "ENABLE_STEAM_AUTH_MODAL_TOASTS",

  // Sub-Sections and Features under CommunityFeedbackCard
  ENABLE_COMMUNITYFEEDBACK_CARD = "ENABLE_COMMUNITYFEEDBACK_CARD",
  ENABLE_COMMUNITYFEEDBACK_LEAVE_REVIEW = "ENABLE_COMMUNITYFEEDBACK_LEAVE_REVIEW",
  ENABLE_COMMUNITYFEEDBACK_MAKE_SUGGESTION = "ENABLE_COMMUNITYFEEDBACK_MAKE_SUGGESTION",

  // Sub-Sections and Features under ChangelogCard
  ENABLE_CHANGELOG_CARD = "ENABLE_CHANGELOG_CARD",
  ENABLE_CHANGELOG_VIEW_ALL = "ENABLE_CHANGELOG_VIEW_ALL",
  ENABLE_CHANGELOG_REACTIONS = "ENABLE_CHANGELOG_REACTIONS",
  ENABLE_CHANGELOG_REACTIONS_POPOVER = "ENABLE_CHANGELOG_REACTIONS_POPOVER",

  // Sub-Sections and Features under Footer
  ENABLE_FOOTER = "ENABLE_FOOTER",
  ENABLE_FOOTER_TEXT = "ENABLE_FOOTER_TEXT",
  ENABLE_FOOTER_ICON = "ENABLE_FOOTER_ICON",
  ENABLE_FOOTER_ABOUT_US = "ENABLE_FOOTER_ABOUT_US",
  ENABLE_FOOTER_QUICK_LINKS = "ENABLE_FOOTER_QUICK_LINKS",
  ENABLE_FOOTER_COMMUNITY = "ENABLE_FOOTER_COMMUNITY",
  ENABLE_FOOTER_LEGAL_FEEDBACK = "ENABLE_FOOTER_LEGAL_FEEDBACK",
  ENABLE_FOOTER_SOCIAL_LINKS = "ENABLE_FOOTER_SOCIAL_LINKS",
  ENABLE_FOOTER_COPYRIGHT = "ENABLE_FOOTER_COPYRIGHT",

  // Sub-Sections and Features under CookieBanner
  ENABLE_COOKIEBANNER = "ENABLE_COOKIEBANNER",
  ENABLE_COOKIEBANNER_ACCEPT = "ENABLE_COOKIEBANNER_ACCEPT",
  ENABLE_COOKIEBANNER_REJECT = "ENABLE_COOKIEBANNER_REJECT",
  ENABLE_COOKIEBANNER_ICON = "ENABLE_COOKIEBANNER_ICON",
  ENABLE_COOKIEBANNER_TEXT = "ENABLE_COOKIEBANNER_TEXT",




  // Independent Features
}

export interface FeatureFlags {
  // Root Feature
  [FeatureFlagKeys.ENABLE]: boolean;

  // Parent Feature
  [FeatureFlagKeys.ENABLE_SETTINGS]: boolean;

  // Sub-Sections and Features under AuthModal
  [FeatureFlagKeys.ENABLE_AUTH_MODAL]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_WELCOME_VIEW]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_SIGNUP_VIEW]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_LOGIN_VIEW]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_SETUSERNAME_VIEW]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_TOASTS]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_ANIMATIONS]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_FOOTER]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_BACK_BUTTON]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_CONTEXT_MESSAGE]: boolean;
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_ERROR_MESSAGES]: boolean;

  // Main Tabs under ENABLE_SETTINGS
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_ACCOUNT
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_BONUS_XP]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_SELF_LOCK]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_SECURITY
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_AFFILIATES
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_OPTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_UNLINK_STEAM]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_DEV_MODE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_FAIRNESS]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_TRANSACTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_PAGINATION]: boolean;

  // Sub-Sections and Features under MainPage
  [FeatureFlagKeys.ENABLE_MAINPAGE_USER_PROFILE]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_LIVE_FEED]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_RECENT_POSTS]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_NEWS]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_CHANGELOG]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_QUICK_ACTIONS]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_USER_STATS]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_SERVER_STATUS]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_BLOG_POSTS]: boolean;
  [FeatureFlagKeys.ENABLE_MAINPAGE_COMMUNITY_FEEDBACK]: boolean;

  // Sub-Sections and Features under UserProfileCard
  [FeatureFlagKeys.ENABLE_USERPROFILE_ACHIEVEMENTS]: boolean;
  [FeatureFlagKeys.ENABLE_USERPROFILE_STATS]: boolean;
  [FeatureFlagKeys.ENABLE_USERPROFILE_RANK]: boolean;

  // Sub-Sections and Features under UserStatsCard
  [FeatureFlagKeys.ENABLE_USERSTATS_RATING]: boolean;
  [FeatureFlagKeys.ENABLE_USERSTATS_PROGRESS]: boolean;
  [FeatureFlagKeys.ENABLE_USERSTATS_TOTAL_JUMPS]: boolean;
  [FeatureFlagKeys.ENABLE_USERSTATS_AVG_SPEED]: boolean;
  [FeatureFlagKeys.ENABLE_USERSTATS_FAVORITE_MAP]: boolean;
  [FeatureFlagKeys.ENABLE_USERSTATS_RANK]: boolean;
  [FeatureFlagKeys.ENABLE_USERSTATS_XP_LEVEL]: boolean;

  // Sub-Sections and Features under ServerStatusCard
  [FeatureFlagKeys.ENABLE_SERVERSTATUS_CARD]: boolean;
  [FeatureFlagKeys.ENABLE_SERVERSTATUS_JOIN_BUTTON]: boolean;
  [FeatureFlagKeys.ENABLE_SERVERSTATUS_TOOLTIPS]: boolean;

  // Sub-Sections and Features under LiveFeedCard
  [FeatureFlagKeys.ENABLE_LIVEFEED_CARD]: boolean;
  [FeatureFlagKeys.ENABLE_LIVEFEED_DIALOG]: boolean;

  // Sub-Sections and Features under NewsCard
  [FeatureFlagKeys.ENABLE_NEWSCARD]: boolean;
  [FeatureFlagKeys.ENABLE_NEWSCARD_VIEW_ALL]: boolean;
  [FeatureFlagKeys.ENABLE_NEWSCARD_POST_LIST]: boolean;

  [FeatureFlagKeys.ENABLE_NEWSCARD_REACTIONS]: boolean;
  [FeatureFlagKeys.ENABLE_NEWSCARD_POPOVER]: boolean;

  // Sub-Sections and Features under RecentPostsCard
  [FeatureFlagKeys.ENABLE_RECENTPOSTS_CARD]: boolean;
  [FeatureFlagKeys.ENABLE_RECENTPOSTS_VIEW_ALL]: boolean;
  [FeatureFlagKeys.ENABLE_RECENTPOSTS_POST_LIST]: boolean;

  // Sub-Sections and Features under QuickActionsCard
  [FeatureFlagKeys.ENABLE_QUICKACTIONS_CARD]: boolean;
  [FeatureFlagKeys.ENABLE_QUICKACTIONS_HOVER_OVERLAY]: boolean;

  // Sub-Sections and Features under BlogPostsCard
  [FeatureFlagKeys.ENABLE_BLOG_POSTS_CARD]: boolean;
  [FeatureFlagKeys.ENABLE_BLOG_POSTS_VIEW_ALL]: boolean;

  // Sub-Sections and Features under SteamAuthModal
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL]: boolean;
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_ANIMATIONS]: boolean;
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_RELAUNCH_BUTTON]: boolean;
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_POPUP_FEATURE]: boolean;
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_FOOTER]: boolean;
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_ERROR_MESSAGES]: boolean;
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_CONTEXT_MESSAGE]: boolean;
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_TOASTS]: boolean;

  // Sub-Sections and Features under CommunityFeedbackCard
  [FeatureFlagKeys.ENABLE_COMMUNITYFEEDBACK_CARD]: boolean;
  [FeatureFlagKeys.ENABLE_COMMUNITYFEEDBACK_LEAVE_REVIEW]: boolean;
  [FeatureFlagKeys.ENABLE_COMMUNITYFEEDBACK_MAKE_SUGGESTION]: boolean;

  // Sub-Sections and Features under ChangelogCard
  [FeatureFlagKeys.ENABLE_CHANGELOG_CARD]: boolean;
  [FeatureFlagKeys.ENABLE_CHANGELOG_VIEW_ALL]: boolean;
  [FeatureFlagKeys.ENABLE_CHANGELOG_REACTIONS]: boolean;
  [FeatureFlagKeys.ENABLE_CHANGELOG_REACTIONS_POPOVER]: boolean;

  // Sub-Sections and Features under Footer
  [FeatureFlagKeys.ENABLE_FOOTER]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_TEXT]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_ICON]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_ABOUT_US]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_QUICK_LINKS]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_COMMUNITY]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_LEGAL_FEEDBACK]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_SOCIAL_LINKS]: boolean;
  [FeatureFlagKeys.ENABLE_FOOTER_COPYRIGHT]: boolean;

  // Sub-Sections and Features under CookieBanner
  [FeatureFlagKeys.ENABLE_COOKIEBANNER]: boolean;
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_ACCEPT]: boolean;
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_REJECT]: boolean;
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_ICON]: boolean;
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_TEXT]: boolean;

  // Independent Features
}

export const featureFlags: FeatureFlags = {
  // Root Feature
  [FeatureFlagKeys.ENABLE]: true,

  // Parent Feature
  [FeatureFlagKeys.ENABLE_SETTINGS]: true,

  // Sub-Sections and Features under AuthModal
  [FeatureFlagKeys.ENABLE_AUTH_MODAL]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_WELCOME_VIEW]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_SIGNUP_VIEW]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_LOGIN_VIEW]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_SETUSERNAME_VIEW]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_TOASTS]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_ANIMATIONS]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_FOOTER]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_BACK_BUTTON]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_CONTEXT_MESSAGE]: true,
  [FeatureFlagKeys.ENABLE_AUTH_MODAL_ERROR_MESSAGES]: true,

  // Main Tabs under ENABLE_SETTINGS
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS]: false,

  // Sub-Sections and Features under ENABLE_SETTINGS_ACCOUNT
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_BONUS_XP]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_SELF_LOCK]: false,

  // Sub-Sections and Features under ENABLE_SETTINGS_SECURITY
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE]: false,

  // Sub-Sections and Features under ENABLE_SETTINGS_AFFILIATES
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS]: false,

  // Sub-Sections and Features under ENABLE_SETTINGS_OPTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_UNLINK_STEAM]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE]:
    false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS]:
    false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS]:
    false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_DEV_MODE]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_FAIRNESS]: false,

  // Sub-Sections and Features under SteamAuthModal
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL]: true,
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_ANIMATIONS]: true,
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_RELAUNCH_BUTTON]: true,
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_POPUP_FEATURE]: true,
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_FOOTER]: true,
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_ERROR_MESSAGES]: true,
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_CONTEXT_MESSAGE]: true,
  [FeatureFlagKeys.ENABLE_STEAM_AUTH_MODAL_TOASTS]: true,

  // Sub-Sections and Features under ENABLE_SETTINGS_TRANSACTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE]: false,
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_PAGINATION]: false,

  // Sub-Sections and Features under MainPage
  [FeatureFlagKeys.ENABLE_MAINPAGE_USER_PROFILE]: true,
  [FeatureFlagKeys.ENABLE_MAINPAGE_LIVE_FEED]: false,
  [FeatureFlagKeys.ENABLE_MAINPAGE_RECENT_POSTS]: false,
  [FeatureFlagKeys.ENABLE_MAINPAGE_NEWS]: false,
  [FeatureFlagKeys.ENABLE_MAINPAGE_CHANGELOG]: false,
  [FeatureFlagKeys.ENABLE_MAINPAGE_QUICK_ACTIONS]: false,
  [FeatureFlagKeys.ENABLE_MAINPAGE_USER_STATS]: true,
  [FeatureFlagKeys.ENABLE_MAINPAGE_SERVER_STATUS]: false,
  [FeatureFlagKeys.ENABLE_MAINPAGE_BLOG_POSTS]: false,
  [FeatureFlagKeys.ENABLE_MAINPAGE_COMMUNITY_FEEDBACK]: false,

  // Sub-Sections and Features under UserProfileCard
  [FeatureFlagKeys.ENABLE_USERPROFILE_ACHIEVEMENTS]: false,
  [FeatureFlagKeys.ENABLE_USERPROFILE_STATS]: false,
  [FeatureFlagKeys.ENABLE_USERPROFILE_RANK]: false,

  // Sub-Sections and Features under UserStatsCard
  [FeatureFlagKeys.ENABLE_USERSTATS_RATING]: false,
  [FeatureFlagKeys.ENABLE_USERSTATS_PROGRESS]: false,
  [FeatureFlagKeys.ENABLE_USERSTATS_TOTAL_JUMPS]: false,
  [FeatureFlagKeys.ENABLE_USERSTATS_AVG_SPEED]: false,
  [FeatureFlagKeys.ENABLE_USERSTATS_FAVORITE_MAP]: false,
  [FeatureFlagKeys.ENABLE_USERSTATS_RANK]: false,
  [FeatureFlagKeys.ENABLE_USERSTATS_XP_LEVEL]: false,

  // Sub-Sections and Features under ServerStatusCard
  [FeatureFlagKeys.ENABLE_SERVERSTATUS_CARD]: false,
  [FeatureFlagKeys.ENABLE_SERVERSTATUS_JOIN_BUTTON]: false,
  [FeatureFlagKeys.ENABLE_SERVERSTATUS_TOOLTIPS]: false,

  // Sub-Sections and Features under LiveFeedCard
  [FeatureFlagKeys.ENABLE_LIVEFEED_CARD]: false,
  [FeatureFlagKeys.ENABLE_LIVEFEED_DIALOG]: false,

  // Sub-Sections and Features under NewsCard
  [FeatureFlagKeys.ENABLE_NEWSCARD]: false,
  [FeatureFlagKeys.ENABLE_NEWSCARD_VIEW_ALL]: false,
  [FeatureFlagKeys.ENABLE_NEWSCARD_POST_LIST]: false,
  [FeatureFlagKeys.ENABLE_NEWSCARD_REACTIONS]: false,
  [FeatureFlagKeys.ENABLE_NEWSCARD_POPOVER]: false,

  // Sub-Sections and Features under RecentPostsCard
  [FeatureFlagKeys.ENABLE_RECENTPOSTS_CARD]: false,
  [FeatureFlagKeys.ENABLE_RECENTPOSTS_VIEW_ALL]: false,
  [FeatureFlagKeys.ENABLE_RECENTPOSTS_POST_LIST]: false,

  // Sub-Sections and Features under QuickActionsCard
  [FeatureFlagKeys.ENABLE_QUICKACTIONS_CARD]: false,
  [FeatureFlagKeys.ENABLE_QUICKACTIONS_HOVER_OVERLAY]: false,

  // Sub-Sections and Features under BlogPostsCard
  [FeatureFlagKeys.ENABLE_BLOG_POSTS_CARD]: false,
  [FeatureFlagKeys.ENABLE_BLOG_POSTS_VIEW_ALL]: false,

  // Sub-Sections and Features under CommunityFeedbackCard
  [FeatureFlagKeys.ENABLE_COMMUNITYFEEDBACK_CARD]: false,
  [FeatureFlagKeys.ENABLE_COMMUNITYFEEDBACK_LEAVE_REVIEW]: false,
  [FeatureFlagKeys.ENABLE_COMMUNITYFEEDBACK_MAKE_SUGGESTION]: false,

  // Sub-Sections and Features under ChangelogCard
  [FeatureFlagKeys.ENABLE_CHANGELOG_CARD]: false,
  [FeatureFlagKeys.ENABLE_CHANGELOG_VIEW_ALL]: false,
  [FeatureFlagKeys.ENABLE_CHANGELOG_REACTIONS]: false,
  [FeatureFlagKeys.ENABLE_CHANGELOG_REACTIONS_POPOVER]: false,

  // Sub-Sections and Features under Footer
  [FeatureFlagKeys.ENABLE_FOOTER]: true,
  [FeatureFlagKeys.ENABLE_FOOTER_TEXT]: true,
  [FeatureFlagKeys.ENABLE_FOOTER_ICON]: true,
  [FeatureFlagKeys.ENABLE_FOOTER_ABOUT_US]: false,
  [FeatureFlagKeys.ENABLE_FOOTER_QUICK_LINKS]: true,
  [FeatureFlagKeys.ENABLE_FOOTER_COMMUNITY]: false,
  [FeatureFlagKeys.ENABLE_FOOTER_LEGAL_FEEDBACK]: false,
  [FeatureFlagKeys.ENABLE_FOOTER_SOCIAL_LINKS]: false,
  [FeatureFlagKeys.ENABLE_FOOTER_COPYRIGHT]: true,

  // Sub-Sections and Features under CookieBanner
  [FeatureFlagKeys.ENABLE_COOKIEBANNER]: false,
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_ACCEPT]: false,
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_REJECT]: false,
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_ICON]: false,
  [FeatureFlagKeys.ENABLE_COOKIEBANNER_TEXT]: false,

  // Independent Features
};
