// utils/featureFlags.ts

export enum FeatureFlagKeys {
  // Root Feature
  ENABLE = "ENABLE",

  // Parent Feature
  ENABLE_SETTINGS = "ENABLE_SETTINGS",

  // Main Tabs under ENABLE_SETTINGS
  ENABLE_SETTINGS_ACCOUNT = "ENABLE_SETTINGS_ACCOUNT",
  ENABLE_SETTINGS_SECURITY = "ENABLE_SETTINGS_SECURITY",
  ENABLE_SETTINGS_AFFILIATES = "ENABLE_SETTINGS_AFFILIATES",
  ENABLE_SETTINGS_OPTIONS = "ENABLE_SETTINGS_OPTIONS",
  ENABLE_SETTINGS_TRANSACTIONS = "ENABLE_SETTINGS_TRANSACTIONS",

  // Sub-Sections and Features under ENABLE_SETTINGS_ACCOUNT
  ENABLE_SETTINGS_ACCOUNT_BONUS_XP = "ENABLE_SETTINGS_ACCOUNT_BONUS_XP",
  ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY = "ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY",
  ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES = "ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES",
  ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL = "ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL",
  ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS = "ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS",
  ENABLE_SETTINGS_ACCOUNT_SELF_LOCK = "ENABLE_SETTINGS_ACCOUNT_SELF_LOCK",

  // Sub-Sections and Features under ENABLE_SETTINGS_SECURITY
  ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH = "ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH",
  ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS = "ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS",
  ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE = "ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE",

  // Sub-Sections and Features under ENABLE_SETTINGS_AFFILIATES
  ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE = "ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE",
  ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS = "ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS",
  ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS = "ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS",
  ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS = "ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS",

  // Sub-Sections and Features under ENABLE_SETTINGS_OPTIONS
  ENABLE_SETTINGS_OPTIONS_ACCOUNT = "ENABLE_SETTINGS_OPTIONS_ACCOUNT",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS",
  ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS = "ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS",
  ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS = "ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM",
  ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS = "ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE",
  ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE = "ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE",
  ENABLE_SETTINGS_OPTIONS_AUDIO = "ENABLE_SETTINGS_OPTIONS_AUDIO",
  ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME = "ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME",
  ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME = "ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME",
  ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME = "ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME",
  ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS = "ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS",
  ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS = "ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS",
  ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS = "ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS",
  ENABLE_SETTINGS_OPTIONS_DEV_MODE = "ENABLE_SETTINGS_OPTIONS_DEV_MODE",
  ENABLE_SETTINGS_OPTIONS_FAIRNESS = "ENABLE_SETTINGS_OPTIONS_FAIRNESS",

  // Sub-Sections and Features under ENABLE_SETTINGS_TRANSACTIONS
  ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE = "ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE",
  ENABLE_SETTINGS_TRANSACTIONS_PAGINATION = "ENABLE_SETTINGS_TRANSACTIONS_PAGINATION",

  // Independent Features
}

export interface FeatureFlags {
  // Root Feature
  [FeatureFlagKeys.ENABLE]: boolean;

  // Parent Feature
  [FeatureFlagKeys.ENABLE_SETTINGS]: boolean;

  // Main Tabs under ENABLE_SETTINGS
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_ACCOUNT
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_BONUS_XP]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_SELF_LOCK]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_SECURITY
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_AFFILIATES
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_OPTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_DEV_MODE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_FAIRNESS]: boolean;

  // Sub-Sections and Features under ENABLE_SETTINGS_TRANSACTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE]: boolean;
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_PAGINATION]: boolean;

  // Independent Features
}

export const featureFlags: FeatureFlags = {
  // Root Feature
  [FeatureFlagKeys.ENABLE]: true,

  // Parent Feature
  [FeatureFlagKeys.ENABLE_SETTINGS]: true,

  // Main Tabs under ENABLE_SETTINGS
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS]: true,

  // Sub-Sections and Features under ENABLE_SETTINGS_ACCOUNT
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_BONUS_XP]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_DISPLAY]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_LEVEL_CASES]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_REDEEM_REFERRAL]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_FREE_REWARDS_STATS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_ACCOUNT_SELF_LOCK]: true,

  // Sub-Sections and Features under ENABLE_SETTINGS_SECURITY
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_FACTOR_AUTH]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_TWO_ACTIVE_SESSIONS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_SECURITY_LOGOUT_EVERYWHERE]: true, // Set to false to disable by default

  // Sub-Sections and Features under ENABLE_SETTINGS_AFFILIATES
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_REFERRAL_CODE]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_STATISTICS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_RECENT_REFERRALS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_AFFILIATES_AFFILIATE_TERMS]: true,

  // Sub-Sections and Features under ENABLE_SETTINGS_OPTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_DISPLAY_NAME]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_STEAM_TRADE_URL]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_HIDE_STATS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_ACCOUNT_EMAIL_ADDRESS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_BLOCKED_USERS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_DISCORD]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_STEAM]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_CONNECTIONS_RECEIVE_PROMOS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_CHAT_ON_RIGHT_SIDE]:
    true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_STREAMER_MODE]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_USER_INTERFACE_LANGUAGE]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_MAIN_VOLUME]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_LIVE_FEED_VOLUME]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_AUDIO_NOTIFICATIONS_VOLUME]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_DISABLE_HELP_TOURS]:
    true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_TIPS_AND_TOURS_RESET_ALL_TOURS]:
    true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_DEV_MODE]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_OPTIONS_FAIRNESS]: true,

  // Sub-Sections and Features under ENABLE_SETTINGS_TRANSACTIONS
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_VIEW_TABLE]: true,
  [FeatureFlagKeys.ENABLE_SETTINGS_TRANSACTIONS_PAGINATION]: true,

  // Independent Features
};
